### ISSUE TITLE
Supporting HA 2021.12 and later

### ISSUE THREAD

**Issue by DarkWolf7** [jdeath/SageTVHomeassistant#2]
Hey there, looks like device_state_attributes was deprecated. After updating to 2012.12.1, the sensor.sagetv was no longer populating the data attribute. I was able to fix it by updating the following:

from:
`    def device_state_attributes(self):`

to:
`    def extra_state_attributes(self):`

I would put in a pull request, but I don't have a python dev environment set up and it seems like overkill for this one liner fix.

**Comment by jdeath** [comment]
Thanks. I’ll make the change tonight. I fixed the not populating issue by
removing an if statement in the device-state-attribute function , but did
not know the function name needed to change

**Comment by pzakrzep** [comment]
@jdeath I know this is an old thread, but should this still be working with HA 2015? I am getting the following while trying to configure.

Logger: homeassistant.config
Source: config.py:942
First occurred: January 4, 2025 at 5:37:45 PM (2 occurrences)
Last logged: January 4, 2025 at 5:37:48 PM

Platform error: sensor - Integration 'sagetv' not found.
Platform error: media_player - Integration 'sagetv' not found.

**Comment by jdeath** [comment]
The latest home assistant depreciated a constant in 2025.1.0 , so you need to update your sensor.py from the repo. 

However, that has not seemed to fix the media player part. I need to look into that.

**Comment by pzakrzep** [comment]
![configuration yaml](https://github.com/user-attachments/assets/77796267-952b-401a-9a23-507373c0f3a4)

@jdeath Thanks for the quick response. I copied the new file, but still the same error? Seems like I may be missing something. I followed the instructions. I assume the configuration goes in the configuration.yaml file? Looks like it is not recognizing the integration sagetv. Is there other config I need somewhere? See attached configuration.yaml.

sensor:
 - platform: sagetv
    scan_interval: 3600
    sagex: http://192.168.1.2:8080/
    posterdir: "/home/homeassistant/.homeassistant/www/posters/"
    posterurl: https://your.domain.com/local/posters/

media_player:
   - platform: sagetv
     name: Bedroom Sage
     extender: XXXXXXXXXXX
     sagex: "http://192.168.1.X:8080/"

**Comment by pzakrzep** [comment]
Looks like I was missing the manifest.json. Now I get the following,

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
First occurred: 9:31:26 AM (1 occurrences)
Last logged: 9:31:26 AM

Failed to load integration for translation: Integration 'sagetv' not found.


Logger: homeassistant.config
Source: config.py:942
First occurred: 9:31:28 AM (2 occurrences)
Last logged: 9:31:31 AM

Platform error: sensor - Integration 'sagetv' not found.
Platform error: media_player - Integration 'sagetv' not found.

**Comment by jdeath** [comment]
Fixed with v1.3 . It was more stuff they depreciated but did not mention in the release notes.

Reopen if still have issues. You need the new media_player.py

**Comment by pzakrzep** [comment]
@jdeath Thanks again. Do you know why I why I would be getting this?

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
First occurred: 10:43:16 AM (1 occurrences)
Last logged: 10:43:16 AM

Failed to load integration for translation: Integration 'sagetv' not found.

**Comment by jdeath** [comment]
Does it not work? It does not support translation, but it should work without them. I do not get that error. Make sure you download all the file from the repo
